platform :ios, '9.0'

target 'pocketFactory' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pocketFactory
  pod 'Alamofire', '~> 4.6'
end
